calculateCDFParamsForPlot <- function(model.cdf){
  # Computes the parameter for the Cumulative Density Function values of
  # the Diffusion Model and the empirical values from the raw data
  # This function uses the .lst file which is created by plot-cdf.exe
  # and is returned by composeCDFparameters.R.
  # It creates objects that hold the parameters of the CDFunction divided
  # by correct and false answers.
  #
  # Args:
  #   model.cdf: A list of cdf parameters, created by a system call
  #   to plot-cdf.exe. This is a mandatory parameter.
  # Uses:
  #   The raw data from the global environment.
  # Returns:
  #   No return value, but created objects are being added to the
  #   global environment.

  cat("Working with", length(dat), "subjects.\n")

  RTcdf_incorr.model <- list()
  RTcdf_corr.model <- list()

  RT_incorrDARK <- list()
  RT_incorrLIGHT <- list()
  RT_corrDARK <- list()
  RT_corrLIGHT <- list()

  empirical_cdf_corrDARK <- list()
  empirical_cdf_corrLIGHT <- list()
  empirical_cdf_incorrDARK <- list()
  empirical_cdf_incorrLIGHT <- list()

  # fading function values for dark and light conditions
  DARK <- -1
  LIGHT <- c(0,800)

  for (s in 1:length(dat)){
    cat("Calculating CDFs for subject", s, "\n")

    # model CDF values for correct and false responses for every subject
    RTcdf_corr.model  [[s]] <- model.cdf[[s]][which(model.cdf[[s]][1] >  0), ]
    RTcdf_incorr.model[[s]] <- model.cdf[[s]][which(model.cdf[[s]][1] <= 0), ]

    # empirical cdf values for correct and false response per condition
    RT_corrDARK  [[s]] <- dat[[s]]$reactionTime_PT[which(dat[[s]]$correct == 1 & dat[[s]]$fading_function == DARK)]
    RT_incorrDARK[[s]] <- dat[[s]]$reactionTime_PT[which(dat[[s]]$correct == 0 & dat[[s]]$fading_function == DARK)]
    RT_corrLIGHT[[s]]  <- dat[[s]]$reactionTime_PT[which(dat[[s]]$correct == 1 & dat[[s]]$fading_function %in% LIGHT)]
    RT_incorrLIGHT[[s]]<- dat[[s]]$reactionTime_PT[which(dat[[s]]$correct == 0 & dat[[s]]$fading_function %in% LIGHT)]

    empirical_cdf_corrDARK  [[s]] <- ecdf(RT_corrDARK[[s]])
    empirical_cdf_incorrDARK[[s]] <- ecdf(RT_incorrDARK[[s]])
    empirical_cdf_corrLIGHT [[s]] <- ecdf(RT_corrLIGHT[[s]])
    empirical_cdf_incorrLIGHT[[s]] <- ecdf(RT_incorrLIGHT[[s]])

    #
    # SHIFT for incorrect responses generated by model and output from plot-cdf.
    #

    # x values
    RTcdf_incorr.model[[s]][1] <- (RTcdf_incorr.model[[s]][1]) * -1

    # y values
    max.Y <- max(RTcdf_incorr.model[[s]][2])
    RTcdf_incorr.model[[s]][2] <- (max.Y - RTcdf_incorr.model[[s]][2]) / max.Y


    #
    # SHIFT for correct responses generated by model and output from plot-cdf
    #
    RTcdf_corr.model[[s]][2] <- (RTcdf_corr.model[[s]][2] - max.Y) / (1 - max.Y)
  }


  # declare all objects global so that they are in the global environment
  assign("RTcdf_incorr.model",   RTcdf_incorr.model,   envir = .GlobalEnv)
  assign("RTcdf_corr.model",     RTcdf_corr.model,     envir = .GlobalEnv)

  assign("RT_corrDARK",             RT_corrDARK,              envir = .GlobalEnv)
  assign("RT_corrLIGHT",            RT_corrLIGHT,              envir = .GlobalEnv)

  assign("RT_incorrLIGHT",           RT_incorrLIGHT,              envir = .GlobalEnv)
  assign("RT_incorrDARK",            RT_incorrDARK,            envir = .GlobalEnv)

  assign("empirical_cdf_corrDARK",   empirical_cdf_corrDARK,   envir = .GlobalEnv)
  assign("empirical_cdf_corrLIGHT",  empirical_cdf_corrLIGHT,   envir = .GlobalEnv)

  assign("empirical_cdf_incorrDARK",  empirical_cdf_incorrDARK,   envir = .GlobalEnv)
  assign("empirical_cdf_incorrLIGHT", empirical_cdf_incorrLIGHT, envir = .GlobalEnv)

}
